services:
  db:
    image: postgres:15-alpine
    container_name: ridebot-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  xray:
    image: teddysun/xray:latest
    container_name: ridebot-proxy
    restart: always
    volumes:
      - ./xray/config.json:/etc/xray/config.json
    ports:
      - "10808:10808"

  # 3. Бот
  bot:
    container_name: ridebot-app
    build: .
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - PROXY_URL=socks5://xray:10808
    depends_on:
      db:
        condition: service_healthy
      xray:
        condition: service_started

volumes:
  postgres-data: